### ISSUE TITLE
Need some pointers about the codebase

### ISSUE THREAD

**Issue by tejasvi** [seandorr/portfolio#1]
Hi, I checked out your awesome portfolio and wanted to play around with it. The problem is though I know html and a bit of javascript, I don't know django and I'm being lazy to learn it. I am ashamed and would totally understand if you refuse what I'm about to ask.. Can you post a prefilled template so I understand how it all fits together? For example, after trying multiple things but I have no idea how should I proceed beyond this:
```
import React from 'react';

const About = () => {
	return (
		<>
			About
		</>
	);
}

export default About;
```

**Comment by seandorr** [comment]
Hi!

Thanks for the praise. May I ask how you stumbled upon my portfolio?

My current live portfolio is just static HTML / CSS / JS. The code you're
referencing above and from my GitHub is me recreating the exact same site
but using React, which uses JSX. If you just inspect my site in a browser,
pretty much all of the code you need is there! If you have specific
questions, I'd be more than happy to help - most of my site is just using
CSS to make it look really nice / cool.

Sean

**Comment by tejasvi** [comment]
@seandorr Thanks for the quick reply :) I was earlier trying to use plain html in react. I finally figured it out after relentless poking and googling. Also, <3 the site design!!
